import styled from 'styled-components';
import Octicon from 'react-octicon'

const Gist = ({ gist }) => {
    // console.log("gist", gist);

    const renderGist = (data) => {
        if (data) {
            return (
                <>
                    {
                        Object.keys(data).map((item, i) => {
                            return (
                                <GistContainer key={item + i}>
                                    <GistItem target='blank' href={data[item].raw_url} >
                                        <p>{data[item].filename}</p>
                                    </GistItem>
                                </GistContainer>

                            )
                        })
                    }
                </>
            )
        }
    }


    return (
        <GistWrapper>
            <UserInfo>
                <Avatar src={gist.owner.avatar_url} />
                <InnerWrapper>
                    <TitleContainer>
                        <Title>{gist.owner.login}</Title>
                        <Details>
                            <DetailsItem>
                                <Octicon name="code" />
                                <p style={{ padding: '5px' }}>files</p>
                            </DetailsItem>

                            <DetailsItem>
                                <Octicon name="git-merge" />
                                <p style={{ padding: '5px' }}>Forks</p>
                            </DetailsItem>

                            <DetailsItem>
                                <Octicon name="comment" />
                                <p style={{ padding: '5px' }}>Comments</p>
                            </DetailsItem>

                            <DetailsItem>
                                <Octicon name="star" />
                                <p style={{ padding: '5px' }}>Stars</p>
                            </DetailsItem>
                        </Details>
                    </TitleContainer>
                    <DateWrapper>
                        <Title>Created at: {new Date(gist.created_at).toLocaleDateString()}</Title>
                        <Title>Last Updated: {new Date(gist.updated_at).toLocaleDateString()}</Title>
                    </DateWrapper>

                    <Title>Generated by: {gist.owner.login}</Title>
                    {renderGist(gist.files)}

                </InnerWrapper>
            </UserInfo>

        </GistWrapper>
    )
}

const GistWrapper = styled.div`
display:flex;
padding:10px;
// justify-content:center;
// align-items:center;
`;




const UserInfo = styled.div`
display:flex;
`;

const Avatar = styled.img`
display:flex;
border-radius:50px;
width:50px;
height:50px;
`;

const InnerWrapper = styled.div`
display:flex;
flex-direction:column;
padding:0px;
`;

const Title = styled.div`
display:flex;
font-size:12px;
color:black;
padding-top:5px;
padding-bottom:5px;
`;

const DateWrapper = styled.div`
display:flex;
flex-direction:row;

`

const GistContainer = styled.div`
display:flex;
`;
const GistItem = styled.a`
text-decoration:none;
`
const Details = styled.div`
display:flex;
// width:300px;
// justify-content:space-around;

`

const TitleContainer = styled.div`
display:flex;
flex-direction:row;
align-items:center;
justify-content:space-between;
`;

const DetailsItem = styled.div`
display:flex;
align-items: flex-start;
padding:5px;
height: fit-content;
justify-content: center;
align-items: center;

`
export default Gist
